name: CI

on:
    push:
    pull_request:

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        container:
            image: node:current

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test
